package com.homework.sharding.biz.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public TbOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNull() {
            addCriterion("trans_status is null");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNotNull() {
            addCriterion("trans_status is not null");
            return (Criteria) this;
        }

        public Criteria andTransStatusEqualTo(String value) {
            addCriterion("trans_status =", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotEqualTo(String value) {
            addCriterion("trans_status <>", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThan(String value) {
            addCriterion("trans_status >", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThanOrEqualTo(String value) {
            addCriterion("trans_status >=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThan(String value) {
            addCriterion("trans_status <", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThanOrEqualTo(String value) {
            addCriterion("trans_status <=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLike(String value) {
            addCriterion("trans_status like", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotLike(String value) {
            addCriterion("trans_status not like", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusIn(List<String> values) {
            addCriterion("trans_status in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotIn(List<String> values) {
            addCriterion("trans_status not in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusBetween(String value1, String value2) {
            addCriterion("trans_status between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotBetween(String value1, String value2) {
            addCriterion("trans_status not between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("pay_status is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(String value) {
            addCriterion("pay_status =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(String value) {
            addCriterion("pay_status <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(String value) {
            addCriterion("pay_status >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(String value) {
            addCriterion("pay_status >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(String value) {
            addCriterion("pay_status <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(String value) {
            addCriterion("pay_status <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLike(String value) {
            addCriterion("pay_status like", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotLike(String value) {
            addCriterion("pay_status not like", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<String> values) {
            addCriterion("pay_status in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<String> values) {
            addCriterion("pay_status not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(String value1, String value2) {
            addCriterion("pay_status between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(String value1, String value2) {
            addCriterion("pay_status not between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIsNull() {
            addCriterion("refund_status is null");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIsNotNull() {
            addCriterion("refund_status is not null");
            return (Criteria) this;
        }

        public Criteria andRefundStatusEqualTo(String value) {
            addCriterion("refund_status =", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotEqualTo(String value) {
            addCriterion("refund_status <>", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusGreaterThan(String value) {
            addCriterion("refund_status >", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusGreaterThanOrEqualTo(String value) {
            addCriterion("refund_status >=", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLessThan(String value) {
            addCriterion("refund_status <", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLessThanOrEqualTo(String value) {
            addCriterion("refund_status <=", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLike(String value) {
            addCriterion("refund_status like", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotLike(String value) {
            addCriterion("refund_status not like", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIn(List<String> values) {
            addCriterion("refund_status in", values, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotIn(List<String> values) {
            addCriterion("refund_status not in", values, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusBetween(String value1, String value2) {
            addCriterion("refund_status between", value1, value2, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotBetween(String value1, String value2) {
            addCriterion("refund_status not between", value1, value2, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampIsNull() {
            addCriterion("start_refund_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampIsNotNull() {
            addCriterion("start_refund_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampEqualTo(Date value) {
            addCriterion("start_refund_timestamp =", value, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampNotEqualTo(Date value) {
            addCriterion("start_refund_timestamp <>", value, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampGreaterThan(Date value) {
            addCriterion("start_refund_timestamp >", value, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("start_refund_timestamp >=", value, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampLessThan(Date value) {
            addCriterion("start_refund_timestamp <", value, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampLessThanOrEqualTo(Date value) {
            addCriterion("start_refund_timestamp <=", value, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampIn(List<Date> values) {
            addCriterion("start_refund_timestamp in", values, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampNotIn(List<Date> values) {
            addCriterion("start_refund_timestamp not in", values, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampBetween(Date value1, Date value2) {
            addCriterion("start_refund_timestamp between", value1, value2, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andStartRefundTimestampNotBetween(Date value1, Date value2) {
            addCriterion("start_refund_timestamp not between", value1, value2, "startRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampIsNull() {
            addCriterion("refund_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampIsNotNull() {
            addCriterion("refund_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampEqualTo(Date value) {
            addCriterion("refund_timestamp =", value, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampNotEqualTo(Date value) {
            addCriterion("refund_timestamp <>", value, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampGreaterThan(Date value) {
            addCriterion("refund_timestamp >", value, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("refund_timestamp >=", value, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampLessThan(Date value) {
            addCriterion("refund_timestamp <", value, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampLessThanOrEqualTo(Date value) {
            addCriterion("refund_timestamp <=", value, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampIn(List<Date> values) {
            addCriterion("refund_timestamp in", values, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampNotIn(List<Date> values) {
            addCriterion("refund_timestamp not in", values, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampBetween(Date value1, Date value2) {
            addCriterion("refund_timestamp between", value1, value2, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andRefundTimestampNotBetween(Date value1, Date value2) {
            addCriterion("refund_timestamp not between", value1, value2, "refundTimestamp");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andBusinessDateIsNull() {
            addCriterion("business_date is null");
            return (Criteria) this;
        }

        public Criteria andBusinessDateIsNotNull() {
            addCriterion("business_date is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessDateEqualTo(String value) {
            addCriterion("business_date =", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateNotEqualTo(String value) {
            addCriterion("business_date <>", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateGreaterThan(String value) {
            addCriterion("business_date >", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateGreaterThanOrEqualTo(String value) {
            addCriterion("business_date >=", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateLessThan(String value) {
            addCriterion("business_date <", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateLessThanOrEqualTo(String value) {
            addCriterion("business_date <=", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateLike(String value) {
            addCriterion("business_date like", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateNotLike(String value) {
            addCriterion("business_date not like", value, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateIn(List<String> values) {
            addCriterion("business_date in", values, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateNotIn(List<String> values) {
            addCriterion("business_date not in", values, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateBetween(String value1, String value2) {
            addCriterion("business_date between", value1, value2, "businessDate");
            return (Criteria) this;
        }

        public Criteria andBusinessDateNotBetween(String value1, String value2) {
            addCriterion("business_date not between", value1, value2, "businessDate");
            return (Criteria) this;
        }

        public Criteria andTransAmountIsNull() {
            addCriterion("trans_amount is null");
            return (Criteria) this;
        }

        public Criteria andTransAmountIsNotNull() {
            addCriterion("trans_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTransAmountEqualTo(BigDecimal value) {
            addCriterion("trans_amount =", value, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountNotEqualTo(BigDecimal value) {
            addCriterion("trans_amount <>", value, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountGreaterThan(BigDecimal value) {
            addCriterion("trans_amount >", value, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trans_amount >=", value, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountLessThan(BigDecimal value) {
            addCriterion("trans_amount <", value, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trans_amount <=", value, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountIn(List<BigDecimal> values) {
            addCriterion("trans_amount in", values, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountNotIn(List<BigDecimal> values) {
            addCriterion("trans_amount not in", values, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trans_amount between", value1, value2, "transAmount");
            return (Criteria) this;
        }

        public Criteria andTransAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trans_amount not between", value1, value2, "transAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountIsNull() {
            addCriterion("payment_amount is null");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountIsNotNull() {
            addCriterion("payment_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountEqualTo(BigDecimal value) {
            addCriterion("payment_amount =", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountNotEqualTo(BigDecimal value) {
            addCriterion("payment_amount <>", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountGreaterThan(BigDecimal value) {
            addCriterion("payment_amount >", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("payment_amount >=", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountLessThan(BigDecimal value) {
            addCriterion("payment_amount <", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("payment_amount <=", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountIn(List<BigDecimal> values) {
            addCriterion("payment_amount in", values, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountNotIn(List<BigDecimal> values) {
            addCriterion("payment_amount not in", values, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("payment_amount between", value1, value2, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("payment_amount not between", value1, value2, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampIsNull() {
            addCriterion("payment_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampIsNotNull() {
            addCriterion("payment_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampEqualTo(Date value) {
            addCriterion("payment_timestamp =", value, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampNotEqualTo(Date value) {
            addCriterion("payment_timestamp <>", value, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampGreaterThan(Date value) {
            addCriterion("payment_timestamp >", value, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("payment_timestamp >=", value, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampLessThan(Date value) {
            addCriterion("payment_timestamp <", value, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampLessThanOrEqualTo(Date value) {
            addCriterion("payment_timestamp <=", value, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampIn(List<Date> values) {
            addCriterion("payment_timestamp in", values, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampNotIn(List<Date> values) {
            addCriterion("payment_timestamp not in", values, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampBetween(Date value1, Date value2) {
            addCriterion("payment_timestamp between", value1, value2, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andPaymentTimestampNotBetween(Date value1, Date value2) {
            addCriterion("payment_timestamp not between", value1, value2, "paymentTimestamp");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("out_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("out_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("out_trade_no =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("out_trade_no <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("out_trade_no >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("out_trade_no >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("out_trade_no <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("out_trade_no <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("out_trade_no like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("out_trade_no not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("out_trade_no in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("out_trade_no not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("out_trade_no between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("out_trade_no not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayChannelIsNull() {
            addCriterion("pay_channel is null");
            return (Criteria) this;
        }

        public Criteria andPayChannelIsNotNull() {
            addCriterion("pay_channel is not null");
            return (Criteria) this;
        }

        public Criteria andPayChannelEqualTo(String value) {
            addCriterion("pay_channel =", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotEqualTo(String value) {
            addCriterion("pay_channel <>", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelGreaterThan(String value) {
            addCriterion("pay_channel >", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelGreaterThanOrEqualTo(String value) {
            addCriterion("pay_channel >=", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelLessThan(String value) {
            addCriterion("pay_channel <", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelLessThanOrEqualTo(String value) {
            addCriterion("pay_channel <=", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelLike(String value) {
            addCriterion("pay_channel like", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotLike(String value) {
            addCriterion("pay_channel not like", value, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelIn(List<String> values) {
            addCriterion("pay_channel in", values, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotIn(List<String> values) {
            addCriterion("pay_channel not in", values, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelBetween(String value1, String value2) {
            addCriterion("pay_channel between", value1, value2, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNotBetween(String value1, String value2) {
            addCriterion("pay_channel not between", value1, value2, "payChannel");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameIsNull() {
            addCriterion("pay_channel_name is null");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameIsNotNull() {
            addCriterion("pay_channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameEqualTo(String value) {
            addCriterion("pay_channel_name =", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameNotEqualTo(String value) {
            addCriterion("pay_channel_name <>", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameGreaterThan(String value) {
            addCriterion("pay_channel_name >", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("pay_channel_name >=", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameLessThan(String value) {
            addCriterion("pay_channel_name <", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameLessThanOrEqualTo(String value) {
            addCriterion("pay_channel_name <=", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameLike(String value) {
            addCriterion("pay_channel_name like", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameNotLike(String value) {
            addCriterion("pay_channel_name not like", value, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameIn(List<String> values) {
            addCriterion("pay_channel_name in", values, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameNotIn(List<String> values) {
            addCriterion("pay_channel_name not in", values, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameBetween(String value1, String value2) {
            addCriterion("pay_channel_name between", value1, value2, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andPayChannelNameNotBetween(String value1, String value2) {
            addCriterion("pay_channel_name not between", value1, value2, "payChannelName");
            return (Criteria) this;
        }

        public Criteria andCardOwnerIsNull() {
            addCriterion("card_owner is null");
            return (Criteria) this;
        }

        public Criteria andCardOwnerIsNotNull() {
            addCriterion("card_owner is not null");
            return (Criteria) this;
        }

        public Criteria andCardOwnerEqualTo(String value) {
            addCriterion("card_owner =", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerNotEqualTo(String value) {
            addCriterion("card_owner <>", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerGreaterThan(String value) {
            addCriterion("card_owner >", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("card_owner >=", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerLessThan(String value) {
            addCriterion("card_owner <", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerLessThanOrEqualTo(String value) {
            addCriterion("card_owner <=", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerLike(String value) {
            addCriterion("card_owner like", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerNotLike(String value) {
            addCriterion("card_owner not like", value, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerIn(List<String> values) {
            addCriterion("card_owner in", values, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerNotIn(List<String> values) {
            addCriterion("card_owner not in", values, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerBetween(String value1, String value2) {
            addCriterion("card_owner between", value1, value2, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardOwnerNotBetween(String value1, String value2) {
            addCriterion("card_owner not between", value1, value2, "cardOwner");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNameIsNull() {
            addCriterion("card_name is null");
            return (Criteria) this;
        }

        public Criteria andCardNameIsNotNull() {
            addCriterion("card_name is not null");
            return (Criteria) this;
        }

        public Criteria andCardNameEqualTo(String value) {
            addCriterion("card_name =", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotEqualTo(String value) {
            addCriterion("card_name <>", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameGreaterThan(String value) {
            addCriterion("card_name >", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameGreaterThanOrEqualTo(String value) {
            addCriterion("card_name >=", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameLessThan(String value) {
            addCriterion("card_name <", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameLessThanOrEqualTo(String value) {
            addCriterion("card_name <=", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameLike(String value) {
            addCriterion("card_name like", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotLike(String value) {
            addCriterion("card_name not like", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameIn(List<String> values) {
            addCriterion("card_name in", values, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotIn(List<String> values) {
            addCriterion("card_name not in", values, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameBetween(String value1, String value2) {
            addCriterion("card_name between", value1, value2, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotBetween(String value1, String value2) {
            addCriterion("card_name not between", value1, value2, "cardName");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampIsNull() {
            addCriterion("next_process_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampIsNotNull() {
            addCriterion("next_process_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampEqualTo(Date value) {
            addCriterion("next_process_timestamp =", value, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampNotEqualTo(Date value) {
            addCriterion("next_process_timestamp <>", value, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampGreaterThan(Date value) {
            addCriterion("next_process_timestamp >", value, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("next_process_timestamp >=", value, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampLessThan(Date value) {
            addCriterion("next_process_timestamp <", value, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampLessThanOrEqualTo(Date value) {
            addCriterion("next_process_timestamp <=", value, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampIn(List<Date> values) {
            addCriterion("next_process_timestamp in", values, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampNotIn(List<Date> values) {
            addCriterion("next_process_timestamp not in", values, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampBetween(Date value1, Date value2) {
            addCriterion("next_process_timestamp between", value1, value2, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessTimestampNotBetween(Date value1, Date value2) {
            addCriterion("next_process_timestamp not between", value1, value2, "nextProcessTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountIsNull() {
            addCriterion("next_process_count is null");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountIsNotNull() {
            addCriterion("next_process_count is not null");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountEqualTo(Integer value) {
            addCriterion("next_process_count =", value, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountNotEqualTo(Integer value) {
            addCriterion("next_process_count <>", value, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountGreaterThan(Integer value) {
            addCriterion("next_process_count >", value, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("next_process_count >=", value, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountLessThan(Integer value) {
            addCriterion("next_process_count <", value, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountLessThanOrEqualTo(Integer value) {
            addCriterion("next_process_count <=", value, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountIn(List<Integer> values) {
            addCriterion("next_process_count in", values, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountNotIn(List<Integer> values) {
            addCriterion("next_process_count not in", values, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountBetween(Integer value1, Integer value2) {
            addCriterion("next_process_count between", value1, value2, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextProcessCountNotBetween(Integer value1, Integer value2) {
            addCriterion("next_process_count not between", value1, value2, "nextProcessCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampIsNull() {
            addCriterion("next_refund_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampIsNotNull() {
            addCriterion("next_refund_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampEqualTo(Date value) {
            addCriterion("next_refund_timestamp =", value, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampNotEqualTo(Date value) {
            addCriterion("next_refund_timestamp <>", value, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampGreaterThan(Date value) {
            addCriterion("next_refund_timestamp >", value, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("next_refund_timestamp >=", value, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampLessThan(Date value) {
            addCriterion("next_refund_timestamp <", value, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampLessThanOrEqualTo(Date value) {
            addCriterion("next_refund_timestamp <=", value, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampIn(List<Date> values) {
            addCriterion("next_refund_timestamp in", values, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampNotIn(List<Date> values) {
            addCriterion("next_refund_timestamp not in", values, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampBetween(Date value1, Date value2) {
            addCriterion("next_refund_timestamp between", value1, value2, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundTimestampNotBetween(Date value1, Date value2) {
            addCriterion("next_refund_timestamp not between", value1, value2, "nextRefundTimestamp");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountIsNull() {
            addCriterion("next_refund_count is null");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountIsNotNull() {
            addCriterion("next_refund_count is not null");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountEqualTo(Integer value) {
            addCriterion("next_refund_count =", value, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountNotEqualTo(Integer value) {
            addCriterion("next_refund_count <>", value, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountGreaterThan(Integer value) {
            addCriterion("next_refund_count >", value, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("next_refund_count >=", value, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountLessThan(Integer value) {
            addCriterion("next_refund_count <", value, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountLessThanOrEqualTo(Integer value) {
            addCriterion("next_refund_count <=", value, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountIn(List<Integer> values) {
            addCriterion("next_refund_count in", values, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountNotIn(List<Integer> values) {
            addCriterion("next_refund_count not in", values, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountBetween(Integer value1, Integer value2) {
            addCriterion("next_refund_count between", value1, value2, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andNextRefundCountNotBetween(Integer value1, Integer value2) {
            addCriterion("next_refund_count not between", value1, value2, "nextRefundCount");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeIsNull() {
            addCriterion("send_product_time is null");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeIsNotNull() {
            addCriterion("send_product_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeEqualTo(Date value) {
            addCriterion("send_product_time =", value, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeNotEqualTo(Date value) {
            addCriterion("send_product_time <>", value, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeGreaterThan(Date value) {
            addCriterion("send_product_time >", value, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_product_time >=", value, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeLessThan(Date value) {
            addCriterion("send_product_time <", value, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_product_time <=", value, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeIn(List<Date> values) {
            addCriterion("send_product_time in", values, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeNotIn(List<Date> values) {
            addCriterion("send_product_time not in", values, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeBetween(Date value1, Date value2) {
            addCriterion("send_product_time between", value1, value2, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendProductTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_product_time not between", value1, value2, "sendProductTime");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNull() {
            addCriterion("send_type is null");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNotNull() {
            addCriterion("send_type is not null");
            return (Criteria) this;
        }

        public Criteria andSendTypeEqualTo(String value) {
            addCriterion("send_type =", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotEqualTo(String value) {
            addCriterion("send_type <>", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThan(String value) {
            addCriterion("send_type >", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThanOrEqualTo(String value) {
            addCriterion("send_type >=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThan(String value) {
            addCriterion("send_type <", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThanOrEqualTo(String value) {
            addCriterion("send_type <=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLike(String value) {
            addCriterion("send_type like", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotLike(String value) {
            addCriterion("send_type not like", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeIn(List<String> values) {
            addCriterion("send_type in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotIn(List<String> values) {
            addCriterion("send_type not in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeBetween(String value1, String value2) {
            addCriterion("send_type between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotBetween(String value1, String value2) {
            addCriterion("send_type not between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andShardingIdIsNull() {
            addCriterion("sharding_id is null");
            return (Criteria) this;
        }

        public Criteria andShardingIdIsNotNull() {
            addCriterion("sharding_id is not null");
            return (Criteria) this;
        }

        public Criteria andShardingIdEqualTo(Integer value) {
            addCriterion("sharding_id =", value, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdNotEqualTo(Integer value) {
            addCriterion("sharding_id <>", value, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdGreaterThan(Integer value) {
            addCriterion("sharding_id >", value, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sharding_id >=", value, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdLessThan(Integer value) {
            addCriterion("sharding_id <", value, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdLessThanOrEqualTo(Integer value) {
            addCriterion("sharding_id <=", value, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdIn(List<Integer> values) {
            addCriterion("sharding_id in", values, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdNotIn(List<Integer> values) {
            addCriterion("sharding_id not in", values, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdBetween(Integer value1, Integer value2) {
            addCriterion("sharding_id between", value1, value2, "shardingId");
            return (Criteria) this;
        }

        public Criteria andShardingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sharding_id not between", value1, value2, "shardingId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 05 23:14:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order
     *
     * @mbggenerated Sat Dec 05 23:14:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}