package com.homework.sharding.biz.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.util.Date;

public class TbOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trans_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String transStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.refund_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.start_refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date startRefundTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date refundTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_type
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.business_date
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trans_amount
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private BigDecimal transAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.payment_amount
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private BigDecimal paymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.payment_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date paymentTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.out_trade_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_channel
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_channel_name
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String payChannelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.card_owner
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String cardOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.card_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.card_name
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.next_process_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date nextProcessTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.next_process_count
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Integer nextProcessCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.next_refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date nextRefundTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.next_refund_count
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Integer nextRefundCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.send_product_time
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Date sendProductTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.send_type
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String sendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sharding_id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private Integer shardingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.remark
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.id
     *
     * @return the value of tb_order.id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_no
     *
     * @return the value of tb_order.order_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_no
     *
     * @param orderNo the value for tb_order.order_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trans_status
     *
     * @return the value of tb_order.trans_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trans_status
     *
     * @param transStatus the value for tb_order.trans_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_status
     *
     * @return the value of tb_order.pay_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_status
     *
     * @param payStatus the value for tb_order.pay_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.refund_status
     *
     * @return the value of tb_order.refund_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.refund_status
     *
     * @param refundStatus the value for tb_order.refund_status
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.start_refund_timestamp
     *
     * @return the value of tb_order.start_refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getStartRefundTimestamp() {
        return startRefundTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.start_refund_timestamp
     *
     * @param startRefundTimestamp the value for tb_order.start_refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setStartRefundTimestamp(Date startRefundTimestamp) {
        this.startRefundTimestamp = startRefundTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.refund_timestamp
     *
     * @return the value of tb_order.refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getRefundTimestamp() {
        return refundTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.refund_timestamp
     *
     * @param refundTimestamp the value for tb_order.refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setRefundTimestamp(Date refundTimestamp) {
        this.refundTimestamp = refundTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_type
     *
     * @return the value of tb_order.order_type
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_type
     *
     * @param orderType the value for tb_order.order_type
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.business_date
     *
     * @return the value of tb_order.business_date
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.business_date
     *
     * @param businessDate the value for tb_order.business_date
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setBusinessDate(String businessDate) {
        this.businessDate = businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trans_amount
     *
     * @return the value of tb_order.trans_amount
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public BigDecimal getTransAmount() {
        return transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trans_amount
     *
     * @param transAmount the value for tb_order.trans_amount
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setTransAmount(BigDecimal transAmount) {
        this.transAmount = transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.payment_amount
     *
     * @return the value of tb_order.payment_amount
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public BigDecimal getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.payment_amount
     *
     * @param paymentAmount the value for tb_order.payment_amount
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.payment_timestamp
     *
     * @return the value of tb_order.payment_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getPaymentTimestamp() {
        return paymentTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.payment_timestamp
     *
     * @param paymentTimestamp the value for tb_order.payment_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setPaymentTimestamp(Date paymentTimestamp) {
        this.paymentTimestamp = paymentTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.out_trade_no
     *
     * @return the value of tb_order.out_trade_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.out_trade_no
     *
     * @param outTradeNo the value for tb_order.out_trade_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_channel
     *
     * @return the value of tb_order.pay_channel
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_channel
     *
     * @param payChannel the value for tb_order.pay_channel
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_channel_name
     *
     * @return the value of tb_order.pay_channel_name
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getPayChannelName() {
        return payChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_channel_name
     *
     * @param payChannelName the value for tb_order.pay_channel_name
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setPayChannelName(String payChannelName) {
        this.payChannelName = payChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.card_owner
     *
     * @return the value of tb_order.card_owner
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getCardOwner() {
        return cardOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.card_owner
     *
     * @param cardOwner the value for tb_order.card_owner
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setCardOwner(String cardOwner) {
        this.cardOwner = cardOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.card_no
     *
     * @return the value of tb_order.card_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.card_no
     *
     * @param cardNo the value for tb_order.card_no
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.card_name
     *
     * @return the value of tb_order.card_name
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.card_name
     *
     * @param cardName the value for tb_order.card_name
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_timestamp
     *
     * @return the value of tb_order.create_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_timestamp
     *
     * @param createTimestamp the value for tb_order.create_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.next_process_timestamp
     *
     * @return the value of tb_order.next_process_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getNextProcessTimestamp() {
        return nextProcessTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.next_process_timestamp
     *
     * @param nextProcessTimestamp the value for tb_order.next_process_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setNextProcessTimestamp(Date nextProcessTimestamp) {
        this.nextProcessTimestamp = nextProcessTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.next_process_count
     *
     * @return the value of tb_order.next_process_count
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Integer getNextProcessCount() {
        return nextProcessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.next_process_count
     *
     * @param nextProcessCount the value for tb_order.next_process_count
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setNextProcessCount(Integer nextProcessCount) {
        this.nextProcessCount = nextProcessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.next_refund_timestamp
     *
     * @return the value of tb_order.next_refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getNextRefundTimestamp() {
        return nextRefundTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.next_refund_timestamp
     *
     * @param nextRefundTimestamp the value for tb_order.next_refund_timestamp
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setNextRefundTimestamp(Date nextRefundTimestamp) {
        this.nextRefundTimestamp = nextRefundTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.next_refund_count
     *
     * @return the value of tb_order.next_refund_count
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Integer getNextRefundCount() {
        return nextRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.next_refund_count
     *
     * @param nextRefundCount the value for tb_order.next_refund_count
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setNextRefundCount(Integer nextRefundCount) {
        this.nextRefundCount = nextRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.send_product_time
     *
     * @return the value of tb_order.send_product_time
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Date getSendProductTime() {
        return sendProductTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.send_product_time
     *
     * @param sendProductTime the value for tb_order.send_product_time
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setSendProductTime(Date sendProductTime) {
        this.sendProductTime = sendProductTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.send_type
     *
     * @return the value of tb_order.send_type
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.send_type
     *
     * @param sendType the value for tb_order.send_type
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.sharding_id
     *
     * @return the value of tb_order.sharding_id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public Integer getShardingId() {
        return shardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.sharding_id
     *
     * @param shardingId the value for tb_order.sharding_id
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setShardingId(Integer shardingId) {
        this.shardingId = shardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.remark
     *
     * @return the value of tb_order.remark
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.remark
     *
     * @param remark the value for tb_order.remark
     *
     * @mbggenerated Sun Dec 06 10:53:32 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}