
spring:
  shardingsphere:
    datasource:
      names:
        ds0,ds1
      # 数据源
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 20
          max-lifetime: 30000
          idle-timeout: 30000
          data-source-properties:
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            cachePrepStmts: true
            useServerPrepStmts: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.3.97:3316/test_0?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 20
          max-lifetime: 30000
          idle-timeout: 30000
          data-source-properties:
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            cachePrepStmts: true
            useServerPrepStmts: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.3.97:3326/test_1?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
    sharding:
      # 分库策略
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: test_$->{user_id % 2}
      # 分表策略
      tables:
        tb_order:
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: tb_order_$->{user_id % 8}
              actualDataNodes: = test_$->{0..1}.tb_order_$->{0..7}
    props:
      sql.show: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  address: 127.0.0.1
  port: 8081