spring:
  shardingsphere:
    datasource:
      names:
        datasource0,datasource1
      # 数据源
      datasource0:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 20
          max-lifetime: 30000
          idle-timeout: 30000
          data-source-properties:
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            cachePrepStmts: true
            useServerPrepStmts: true
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.3.97:3316/test_0?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
      datasource1:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 20
          max-lifetime: 30000
          idle-timeout: 30000
          data-source-properties:
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            cachePrepStmts: true
            useServerPrepStmts: true
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.3.97:3326/test_1?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
    sharding:
      # 分库策略
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: datasource$->{user_id % 2}
      # 分表策略
      tables:
        tb_order:
          actual-data-nodes: datasource$->{0..1}.tb_order_$->{0..15}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: tb_order_$->{user_id % 16}
    props:
      sql.show: true
server:
  address: 127.0.0.1
  port: 8081