package com.dollaraccount.mapper;

import com.dollaraccount.mapper.DollarAccount;
import com.dollaraccount.mapper.DollarAccountExample;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DollarAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int countByExample(DollarAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int deleteByExample(DollarAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int insert(DollarAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int insertSelective(DollarAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    List<DollarAccount> selectByExample(DollarAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    DollarAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") DollarAccount record, @Param("example") DollarAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int updateByExample(@Param("record") DollarAccount record, @Param("example") DollarAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int updateByPrimaryKeySelective(DollarAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dollar_account
     *
     * @mbggenerated Wed Dec 16 23:25:28 CST 2020
     */
    int updateByPrimaryKey(DollarAccount record);

    DollarAccount selectByUserId(@Param("userId") String userId);

    int update(@Param("userId") String userId, @Param("payAmount") BigDecimal payAmount);

    int confirm(@Param("userId") String userId, @Param("payAmount") BigDecimal payAmount);

    int cancel(@Param("userId") String userId, @Param("payAmount") BigDecimal payAmount);
}