package com.stock.mapper;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.product_id
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.total_inventory
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    private Integer totalInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.lock_inventory
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    private Integer lockInventory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.product_id
     *
     * @return the value of stock.product_id
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.product_id
     *
     * @param productId the value for stock.product_id
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.total_inventory
     *
     * @return the value of stock.total_inventory
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public Integer getTotalInventory() {
        return totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.total_inventory
     *
     * @param totalInventory the value for stock.total_inventory
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public void setTotalInventory(Integer totalInventory) {
        this.totalInventory = totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.lock_inventory
     *
     * @return the value of stock.lock_inventory
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public Integer getLockInventory() {
        return lockInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.lock_inventory
     *
     * @param lockInventory the value for stock.lock_inventory
     *
     * @mbggenerated Thu Dec 10 22:40:16 CST 2020
     */
    public void setLockInventory(Integer lockInventory) {
        this.lockInventory = lockInventory;
    }
}