package com.renminbiaccount.mapper;

import com.renminbiaccount.mapper.RenminbiAccount;
import com.renminbiaccount.mapper.RenminbiAccountExample;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RenminbiAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int countByExample(RenminbiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int deleteByExample(RenminbiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int insert(RenminbiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int insertSelective(RenminbiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    List<RenminbiAccount> selectByExample(RenminbiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    RenminbiAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") RenminbiAccount record, @Param("example") RenminbiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int updateByExample(@Param("record") RenminbiAccount record, @Param("example") RenminbiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int updateByPrimaryKeySelective(RenminbiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renminbi_account
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    int updateByPrimaryKey(RenminbiAccount record);

    RenminbiAccount selectByUserId(@Param("userId") String userId);

    int update(@Param("userId") String userId, @Param("payAmount") BigDecimal payAmount);

    int confirm(@Param("userId") String userId, @Param("payAmount") BigDecimal payAmount);

    int cancel(@Param("userId") String userId, @Param("payAmount") BigDecimal payAmount);
}