package com.renminbiaccount.mapper;

import java.util.Date;

public class RenminbiAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renminbi_account.id
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renminbi_account.user_id
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renminbi_account.balance
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renminbi_account.freeze_amount
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    private Long freezeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renminbi_account.create_time
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renminbi_account.update_time
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renminbi_account.id
     *
     * @return the value of renminbi_account.id
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renminbi_account.id
     *
     * @param id the value for renminbi_account.id
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renminbi_account.user_id
     *
     * @return the value of renminbi_account.user_id
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renminbi_account.user_id
     *
     * @param userId the value for renminbi_account.user_id
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renminbi_account.balance
     *
     * @return the value of renminbi_account.balance
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renminbi_account.balance
     *
     * @param balance the value for renminbi_account.balance
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renminbi_account.freeze_amount
     *
     * @return the value of renminbi_account.freeze_amount
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public Long getFreezeAmount() {
        return freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renminbi_account.freeze_amount
     *
     * @param freezeAmount the value for renminbi_account.freeze_amount
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public void setFreezeAmount(Long freezeAmount) {
        this.freezeAmount = freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renminbi_account.create_time
     *
     * @return the value of renminbi_account.create_time
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renminbi_account.create_time
     *
     * @param createTime the value for renminbi_account.create_time
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renminbi_account.update_time
     *
     * @return the value of renminbi_account.update_time
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renminbi_account.update_time
     *
     * @param updateTime the value for renminbi_account.update_time
     *
     * @mbggenerated Wed Dec 16 23:26:50 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}